name: Deploy prod 
permissions: write-all
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch: {}

jobs:
  run:
    uses: "evgsh123/otusproject-apps-cd/.github/workflows/prod.yaml@main"
    with:
      name: "frontend"
      JOBID: "${{ github.run_number }}"
      GITHUBSHA: "${{ github.sha }}"
    secrets:
      YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
      MYGITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}
