name: Build and deploy 
permissions: write-all
on:
  push:
    branches: [ main ]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  run:
    uses: "evgsh123/otusproject-apps-cd/.github/workflows/workflow.yaml@main"
    with:
      name: "shippingService"
      JOBID: "${{ github.run_number }}"
    secrets:
      YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
      MYGITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}

